version: '1'

services:
  app1:
    build:
      context: ./app1
    mem_reservation: 128M
    cpus: 0.5

  gateway:
    build:
      context: ./gateway
    ports:
      - 80:80
      - 443:443
    depends_on:
      - app1
    mem_limit: 512M
    mem_reservation: 128M
    cpus: 0.5

networks:
  default:
    external:
      name: local
